fix: Upgrade project to latest version,accessing undefined properties ...
traleor/next-weblog pull request #1
Opened 2024-01-05 22:49 UTC by Formasitchijoh

## Summary
This pull request addresses the following tasks outlined  [here](https://docs.google.com/document/d/1iki5kQ0Daq9j42dwGsICiFZJxKeejqWpKFhp5FETLbM/edit):

- ###  Upgrade Template
 The project has been updated to the latest version of Next.js and its dependency, ensuring compatibility with the latest features and improvements provided by the framework.
- ###  Metadata updates
 No changes were made to the metadata as they were up-to-date.
- ###  Required changes
An error related to accessing undefined properties on navigating to the tutorial route has been fixed. Conditionally chaining the properties ensures a safe return in case a property is undefined.
- ###  Pull Request submission
 This pull request serves as a submission of the completed task, incorporating the upgrades, metadata updates, and required changes.
 
 @itzomen  Please kindly review when you are chanced and provide your feedback

2024-01-05 23:42 UTC, itzomen requested changes

2024-01-05 23:42 UTC, itzomen commented on .env
@Formasitchijoh Never commit environment files, the .env.example is a template used to create your env file so you do not expose secret variables like your API key.

- Delete this file
- Delete the API key and create a new one
- Do not commit environment files

2024-01-05 23:42 UTC, itzomen commented on package.json
You added unnecessary dependencies, only update the dependencies that are present on the project

2024-01-06 05:57 UTC, Formasitchijoh commented on .env
Okay I'll remove that Sir

2024-01-06 05:58 UTC, Formasitchijoh commented on package.json
Okay, I'll remove that

2024-01-06 08:02 UTC, Formasitchijoh commented
@itzomen i made the required changes you requested,

2024-01-06 08:35 UTC, itzomen approved these changes

2024-01-06 08:35 UTC, merged